Make haproxy test conform to exit standard

diff --git a/jobs/test_haproxy b/jobs/test_haproxy
--- a/jobs/test_haproxy
+++ b/jobs/test_haproxy
@@ -11,3 +11,10 @@ ${VPCI_ROOT}/scripts/clone_repo $repo $ref
 cd puppetlabs-haproxy
 ${VPCI_ROOT}/scripts/write_nodeset
 ${VPCI_ROOT}/scripts/run_beaker_rspec
+ret=$?
+echo $ret
+if [ $ret -eq 0 ];then
+    echo 'PASS'
+else
+    echo 'FAIL'
+fi
